### ISSUE TITLE
Further ideas about `drvs` mixin

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/derivatives#7]
via #5 — Currently the `drvs` mixin places a list of derivative ids in the component state and gets a list of their values when using `react-drvs`. I think this intermediate list is problematic for a few reasons:
- You cannot use `react-drvs` with derivatives that have not been "included" using `drvs`, i.e. the ones included via `(drv :some-thing)`.
- The general benefit of using individual `drv` and `react` calls is that you can use them in your component code and they will only be dereferenced/used when the code is actually used (example below). In comparison when using `react-drvs` all derived values are dereferenced/reacted upon. In the example when the derived value for `:b` updates the component will not rerender. Whereas when `react-drvs` is used it would be re-rendered.

```clojure
(defcs test < (drv/drv :a) (drv/drv b)
  [s]
  (if true
    (drv/react s :a)
    (drv/react s :b)))
```

---- 

I'm thinking a solution to both of these issues could be that `react-drvs` takes a list of dervative-ids similar to the `drvs` mixin. To make that usable it would also have to return a map.

```clojure
(react-drvs (if true :a :b) :c (when false :d))
```
which would return a structure like
```clojure
{:a 'value-of-a :c 'value-of-c}
```
This would make the destructuring a little less nice but overall seems like a more flexible approach.

@CmdrDats curious what you think. Others are also invited to weigh in of course. Maybe the flexibility isn't really needed and I'm just thinking to hard about potential issues. 😄

**Comment by CmdrDats** [comment]
Funny you should say this, my original implementation actually worked exactly like this, but then I found a lot of the components I was making pretty much looked akin to:

```clojure
(defcs test < (d/drvs :page/product :page/image :page/variation :page/videolist :page/morestuff)
  [s]
  (let [[product image variation videolist morestuff] 
          (d/react-drvs  :page/product :page/image :page/variation :page/videolist :page/morestuff)]
    ...)
```

Basically copy/paste everytime - not a trainsmash by any means, just extra noise.

I like the idea of returning a map, since you can choose to destructure or just keyword access the map everywhere, which really is rather nice (I'm generally a little bit wary of ordered vector destructuring).

A 'clever-but-potentially-complex' way could be to return a new kind of map (similar to Datomic Entity) that does the d/drv upon keyword access (so you don't have to provide usages upfront). Though, practically, there's nothing inhibiting a `(d/react)` at the call site.

I'm a bit wary of including the `(if true :a :b)` logic at the `react-drv` function level, because that kind of thing will likely have to be duplicated in the component display logic too. Given that you can just `(d/react)` at callsite, probably just referencing the minimal usage set at `(d/react-drvs :c)` (int your example) would be enough.

One option also is to have a single arity function (for state) return all, but if you provide keywords, it returns just those?

**Comment by martinklepsch** [comment]
Hah, yeah that's a good point. I think the `(d/react-drvs state)` (i.e. no kw-args) idea is good to retrieve all derivatives. It should also work for derivatives imported via `(d/drv :page/image)` though. Although maybe we should just drop `d/drv` and only provide `d/drvs` not much value in having different functions when the `d/drvs` one also fulfills the needs of the other.

I'll try to whip something up and open a PR... 

> A 'clever-but-potentially-complex' way could be to return a new kind of map (similar to Datomic Entity) that does the d/drv upon keyword access (so you don't have to provide usages upfront). Though, practically, there's nothing inhibiting a (d/react) at the call site.

Sounds like a nice rabbit hole haha.

**Comment by martinklepsch** [comment]
@CmdrDats I opened a PR #8 — happy about feedback but take your time, no rush :)

**Comment by martinklepsch** [comment]
Closing this in favor of #8

**Comment by CmdrDats** [comment]
but, but.. rabbit hole! who knows what lovely gems of complexity we can spend ages shining up in there?
